Import("env")

from pathlib import Path


PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
WEB_DIR = PROJECT_DIR / "web"
VERSION_FILE = PROJECT_DIR / "VERSION"
GENERATED_HEADER = PROJECT_DIR / "include" / "generated_web_assets.h"
VERSION_TOKEN = "__APP_VERSION__"

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".txt": "text/plain; charset=utf-8",
}


def read_project_version():
    if not VERSION_FILE.exists():
        raise FileNotFoundError(f"missing version file: {VERSION_FILE}")

    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    if not version:
        raise ValueError(f"empty version file: {VERSION_FILE}")

    return version


def render_text_asset(source_path, project_version):
    source_text = source_path.read_text(encoding="utf-8")
    return source_text.replace(VERSION_TOKEN, project_version).encode("utf-8")


def content_type_for(source_path):
    return CONTENT_TYPES.get(source_path.suffix.lower(), "application/octet-stream")


def identifier_for(path_fragment):
    chars = []
    for char in path_fragment:
        if char.isalnum():
            chars.append(char)
        else:
            chars.append("_")
    return "".join(chars)


def format_bytes_as_cpp(data):
    if not data:
        return "  0x00"

    lines = []
    for index in range(0, len(data), 12):
        chunk = data[index:index + 12]
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk))
    return ",\n".join(lines)


def collect_assets(project_version):
    if not WEB_DIR.exists():
        raise FileNotFoundError(f"missing web asset directory: {WEB_DIR}")

    assets = []
    for source_path in sorted(WEB_DIR.rglob("*")):
        if not source_path.is_file():
            continue

        relative_path = source_path.relative_to(WEB_DIR).as_posix()
        asset_paths = [f"/{relative_path}"]
        if relative_path == "index.html":
            asset_paths.insert(0, "/")

        assets.append(
            {
                "identifier": identifier_for(relative_path),
                "paths": asset_paths,
                "content_type": content_type_for(source_path),
                "bytes": render_text_asset(source_path, project_version),
            }
        )

    if not assets:
        raise ValueError(f"no web assets found in {WEB_DIR}")

    return assets


def render_header(project_version, assets):
    lines = [
        "// Generated by tools/build_web_assets.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "struct EmbeddedWebAsset {",
        "  const char *path;",
        "  const char *content_type;",
        "  const uint8_t *data;",
        "  size_t size;",
        "};",
        "",
        f'inline constexpr char kEmbeddedWebAssetVersion[] = "{project_version}";',
        "",
    ]

    for asset in assets:
        lines.append(
            f"inline const uint8_t kEmbeddedWebAsset_{asset['identifier']}[] PROGMEM = {{"
        )
        lines.append(format_bytes_as_cpp(asset["bytes"]))
        lines.append("};")
        lines.append("")

    lines.append("inline const EmbeddedWebAsset kEmbeddedWebAssets[] = {")
    for asset in assets:
        array_name = f"kEmbeddedWebAsset_{asset['identifier']}"
        for asset_path in asset["paths"]:
            lines.append(
                f'  {{"{asset_path}", "{asset["content_type"]}", '
                f"{array_name}, sizeof({array_name})}},"
            )
    lines.append("};")
    lines.append("")
    lines.append(
        "inline constexpr size_t kEmbeddedWebAssetCount = "
        "sizeof(kEmbeddedWebAssets) / sizeof(kEmbeddedWebAssets[0]);"
    )
    lines.append("")

    return "\n".join(lines)


def build_web_assets(*args, **kwargs):
    project_version = read_project_version()
    assets = collect_assets(project_version)
    header = render_header(project_version, assets)

    GENERATED_HEADER.parent.mkdir(parents=True, exist_ok=True)
    if GENERATED_HEADER.exists():
        existing = GENERATED_HEADER.read_text(encoding="utf-8")
        if existing == header:
            print(
                f"[web] embedded assets up-to-date: {GENERATED_HEADER.name}, "
                f"assets={len(assets)}, version={project_version}"
            )
            return

    GENERATED_HEADER.write_text(header, encoding="utf-8")
    total_bytes = sum(len(asset["bytes"]) for asset in assets)
    print(
        f"[web] embedded assets written: {GENERATED_HEADER.name}, "
        f"assets={len(assets)}, bytes={total_bytes}, version={project_version}"
    )


project_version = read_project_version()
env.AppendUnique(CPPDEFINES=[("APP_VERSION", f'\\"{project_version}\\"')])
build_web_assets()
